### PR TITLE
Rename package to beepytweepy

### PR DESCRIPTION
**Pull request by fffergal**
This is so we can install this package and a newer version of the real
tweepy at the same time, and do a controlled migration instead of
everything all at once.

Beepy as in BP, as in Block Party. I wanted to do just beepy but that's
taken on pypi already and want to avoid confusion.

Used these commands to brute force rename everything:
```
git mv tweepy/ beepytweepy
sed -i '' -e 's/tweepy/beepytweepy/g' $(find . -name '*.py')
sed -i '' -e 's/tweepy/beepytweepy/g' $(find . -name '*.json')
```

Tested with:
```
pip install tox
tox -e py37
```

### CODE REVIEW

**Comment by rhymes** [comment]
@fffergal very cool! could you recreate the PR on top of the branch we're using instead of `master`: https://github.com/block-party-studio-company/tweepy/tree/block-party 

Then we can merge it as is and I can start testing it on the main repo :)

Thanks!

**Comment by fffergal** [comment]
Oh yeh! I learned we used a tag after making the changes and didn't go back for it. Lucky I included the instructions in the commit message! I guess we don't need to merge it if we didn't merge the previous changes, just cut a new tag.

**Comment by rhymes** [comment]
@fffergal cool, i'll do the same on the other branch and prepare a new PR, thanks!

**Comment by rhymes** [comment]
Closed in favor of the branch https://github.com/block-party-studio-company/tweepy/tree/beepytweepy

**Pull request closed without merging**
